# vim:ft=sh:fdm=marker

# If not interactive, bail out
[[ $- != *i* ]] && return

# Bash options {{{
# Command name that is a directory name is treated as argument to cd
shopt -s autocd
# Correct minor directory spelling errors with cd
shopt -s cdspell
# Attempt to save all lines of a multi-line command in same history entry
shopt -s cmdhist
# History list is appended, rather than overwritten on exit
shopt -s histappend
# Pattern '**' expansion matches all files and directories and subdirectories
shopt -s globstar
# use physical path
set -o physical
#}}}
# Shell variables {{{
# Don't put the following in the history
HISTIGNORE="${HISTIGNORE}:cd:cd [~-.]:cd ..:tmux:vim:alias:exit:l[slx]:history*:pwd:clear:[bf]g:mount:unmount"
# Don't put commands that begin with space or dupes in history
HISTCONTROL='ignoreboth:erasedups'
# (500) Number of commands to remember in the command history
HISTSIZE=2000
#}}}
# Environmental variables {{{
export VISUAL="vim"
export EDITOR="${VISUAL}"

# less config
# x4 : tabstop 4 (vs 8)
# F  : exit if output fits on one screen
# R  : raw control codes
# S  : chop long lines
# X  : don't send termcap init/deinit
# s  : combine multiple blank lines into 1
export LESS="-x4FRSXs"
export PAGER="less"

# vim as man pager
# Set true to enable vim as man pager
export MANPAGER="/bin/sh -c \"col -b | vim -NRM -c 'runtime ftplugin/man.vim' -c 'set nofoldenable cmdheight=1 showtabline=0 laststatus=0' -c 'setlocal nonumber norelativenumber colorcolumn=' -c 'setfiletype man' -\""

#}}}

# completion
# shellcheck disable=SC1091
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

# FZF (from fzf vim plugin)
__FZF_BASH_SCRIPT="${HOME}/.fzf.bash"
# shellcheck disable=SC1090
[ -f "${__FZF_BASH_SCRIPT}" ] && source "${__FZF_BASH_SCRIPT}"

# [EXPERIMENTAL] prompt (liquidprompt + customizations)
PROMPT_COMMAND="history -a"
__TMUX_SETPWD="${HOME}/.config/dotfiles/tmux/tmux-setpwd.sh"
if [ -f "${__TMUX_SETPWD}" ]; then
	PROMPT_COMMAND="${PROMPT_COMMAND};${TMUX_SETPWD}"
fi

# git clone https://github.com/nojhan/liquidprompt.git
__LIQUIDPROMPT="/usr/local/src/liquidprompt/liquidprompt"
# shellcheck disable=SC1090
[ -f "${__LIQUIDPROMPT}" ] && source "${__LIQUIDPROMPT}"

# [RHEL7] [TMUX1.8] gruvbox terminal colors (from gruvbox vim plugin)
__GRUVBOX_TERM_SCRIPT="${HOME}/.vim/plugged/gruvbox/gruvbox_256palette.sh"
# shellcheck disable SC1090
[ -f "${__GRUVBOX_TERM_SCRIPT}" ] && source "${__GRUVBOX_TERM_SCRIPT}"

# [RHEL7] [TMUX1.8] TMUX TERM workaround
if [[ "${TERM}" =~ "screen" ]] && [[ -v TMUX ]]; then
	TERM="tmux-256color"
	export TERM
fi

## Supporting files (load if present)
__CONFIG_FILES="${HOME}/.config/dotfiles/shell"
if [ -d "${__CONFIG_FILES}" ]; then
	for __CONFIG_FILE in "${__CONFIG_FILES}"/*; do
		# shellcheck disable=SC1090
		source "${__CONFIG_FILE}"
	done
fi
unset __CONFIG_FILES
