# Source user bashrc (if present)
# shellcheck disable=SC1090
[[ -f ~/.bashrc ]] && . ~/.bashrc

# [OSX] iterm2 shell integration
test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

export PATH="$HOME/.cargo/bin:$PATH"
